namespace patentdesign.Models
{
    public enum AccountType
    {
        Individual,
        Corporate,
        Officer,
        Tech
    }
    public enum Roles
    {
        TrademarkSearch,
        TrademarkExaminer,
        TrademarkOpposition,
        TrademarkAcceptance,
        TrademarkCertification,
        TrademarkRegistrar,
        PatentSearch,
        PatentExaminer,
        PatentCertification,
        DesignSearch,
        DesignExaminer,
        DesignCertification,
        PatentDesignRegistrar,
        Ministry,
        SuperAdmin
    }
    public enum NigerianStates
    {
        Abia,
        Adamawa,
        AkwaIbom,
        Anambra,
        Bauchi,
        Bayelsa,
        Benue,
        Borno,
        CrossRiver,
        Delta,
        Ebonyi,
        Edo,
        Ekiti,
        Enugu,
        Gombe,
        Imo,
        Jigawa,
        Kaduna,
        Kano,
        Katsina,
        Kebbi,
        Kogi,
        Kwara,
        Lagos,
        Nasarawa,
        Niger,
        Ogun,
        Ondo,
        Osun,
        Oyo,
        Plateau,
        Rivers,
        Sokoto,
        Taraba,
        Yobe,
        Zamfara,
        FederalCapitalTerritory
    }
}
