namespace patentdesign.Enums
{
    public enum AccountType
    {
        Individual,
        Corporate,
        Officer,
        Tech
    }
    public enum Roles
    {
        User,
        Staff,
        TrademarkSearch,
        TrademarkExaminer,
        TrademarkOpposition,
        TrademarkAcceptance,
        TrademarkCertification,
        TrademarkPublication,
        TrademarkRegistrar,
        PatentSearch,
        PatentExaminer,
        PatentCertification,
        AppealExaminer,
        DesignSearch,
        DesignExaminer,
        DesignCertification,
        PatentDesignRegistrar,
        Finance,
        PermSec,
        Minister,
        Tech,
        SuperAdmin,
        EinaoFinance,
        Pebec,
        HeadOfUnit,
    }
    public enum NigerianStates
    {
        None,
        Abia,
        Adamawa,
        AkwaIbom,
        Anambra,
        Bauchi,
        Bayelsa,
        Benue,
        Borno,
        CrossRiver,
        Delta,
        Ebonyi,
        Edo,
        Ekiti,
        Enugu,
        Gombe,
        Imo,
        Jigawa,
        Kaduna,
        Kano,
        Katsina,
        Kebbi,
        Kogi,
        Kwara,
        Lagos,
        Nasarawa,
        Niger,
        Ogun,
        Ondo,
        Osun,
        Oyo,
        Plateau,
        Rivers,
        Sokoto,
        Taraba,
        Yobe,
        Zamfara,
        FederalCapitalTerritory
    }
    public enum ClericalUpdateTypes
    {
        CorrespondenceInformation,
        DesignInformation,
        CreatorInformation,
        DesignAttachments,
        ApplicantName,
        ApplicantAddress,
        FileClass,
        FileTitle,
        AddApplicant,
        RemoveApplicant,
        AddAndRemoveApplicant,
        EditInventors,
        PriorityInfo,
        TrademarkType
    }

    public enum EmailType
    {
        ResetPassword, Opposition, StatusUpdate, Announcement
    }
    public enum ApplicationUnits
    {
        Search,
        Examination,
        Publication,
        Opposition,
        Acceptance,
        Certificate
    }

}
