using System.Collections.Generic;
using System.Diagnostics;
using patentdesign.Models;

public class ConstantValues
{
    public List<string> AllCountries = new List<string>()
    {
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Austria",
        "Azerbaijan",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Central African Republic",
        "Chad",
        "Channel Islands",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo",
        "Costa Rica",
        "Côte d'Ivoire",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "DR Congo",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Faeroe Islands",
        "Finland",
        "France",
        "French Guiana",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Holy See",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Isle of Man",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nepal",
        "Netherlands",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "North Korea",
        "North Macedonia",
        "Norway",
        "Oman",
        "Pakistan",
        "Panama",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Réunion",
        "Romania",
        "Russia",
        "Rwanda",
        "Saint Helena",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "San Marino",
        "Sao Tome & Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Somalia",
        "South Africa",
        "South Korea",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "State of Palestine",
        "Sudan",
        "Suriname",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "The Bahamas",
        "Timor-Leste",
        "Togo",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Venezuela",
        "Vietnam",
        "Western Sahara",
        "Yemen",
        "Zambia",
        "Zimbabwe",
    };


    public static bool IsImage(string property)
    {
        return property is "designs";
    }

    public static string MapAttachmentProperty(string property)
    {
        switch (property)
        {
            case "pdoc":
                return "Priority Document";
            case "designs":
                return "Design Representation";
            case "nov":
                return "Novelty Statement";
            case "1a":
                return "Form 1A Document";
            case "cs":
                return "Claims and Specifications";
            case "any":
                return "Other Document";
            case "pct":
                return "PCT document";
            case "form2":
                return "Form 2A Document";
            default:
                return "testing";
        }
    }

    public static bool IsPropertyAttachment(string property)
    {
        return string.Equals(property, "Attachments", StringComparison.CurrentCultureIgnoreCase);
    }



    public static string GetFormType(PaymentTypes? formType, string type, string? others = null)
    {
        Debug.Assert(formType != null);
        return formType switch
        {
            PaymentTypes.NewCreation => $"New {type} Application",
            PaymentTypes.Search => $"{type} Search Term {others}",
            PaymentTypes.LicenseRenew => $"{type} License Renewal",
            PaymentTypes.Update => $"{type} Data Update"
        };
    }

    public static readonly string Passage1 =
        "President of the Federal Republic of Nigeria and commander in chief of the armed forces Bola Ahmed Tinubu";

    public static string Passage7 =
        "And where’s the Federal government willing to encourage all inventions which may be for public good is pleased to accede to the request.";

    public static string Passage8 =
        "KNOW YE THEREFORE, that I do by this Instrument give and grant unto the person(s) above named and any successor(s)," +
        " executor(s), administrators) and assign(s) (each and any of whom are hereinafter referred to as the patentee) by special licence," +
        " full power, sole privilege and authority, that the patentee or any agent or licensee of the patentee may subject to the conditions and provisions prescribed by any statute" +
        " or order for the time being ni force at al times hereafter during the term of years herein mentioned, make, use, exercise and vend the said invention throughout the Federal Republic of Nigeria," +
        " and that the patentee shall have and enjoy the whole profit and advantage from time ot time accruing by reason of the said invention during the term of twenty years from the date first above written on this Instrument.";
    public static string Passage11 =
        "AND to the end that the patentee may have and enjoy the sole use and exercise of the full benefit of the said invention. Ido by this Instrument strictly command al citizens of the Federal Republic of Nigeria that they do not at any time during the continuance of the said term either directly" +
        " or indirectly make use of or put ni practice the said invention, nor ni anywise imitate the same, without the written consent, licence or agreement of the patentee, on pain of incurring such penalties as may be justly inflicted on such offenders" +
        ", and of being answerable to the patentee according to law for damages thereby occasioned";

    public static string Passage9 =
        "PROVIDED ALWAYS that this patent shall be revocable on any of the grounds from time ot time by law prescribed as grounds for revoking patents granted yb me, and the same may be revoked and made void accordingly";

    public static string Passage10 =
        "PROVIDED ALSO that nothing herein contained shall prevent the granting of licences in such manner and for such considerations as they may by law be granted";

    public static string DesignCertificate =
        "This is to certify that in pursuance of and subject to the provisions of the patent and designs Act (CAP) 344 LFN 1990) the design of which a representation is annexed has been registered in the name of";

    public static string TrademarkPassage1 =
        "Registration is 7 years from the date first above --mentioned, and may then be renewed, and also at the Expiration of each period of 14 years thereafter.";

    public static string TrademarkPassage2 = "This certificate is not for use in legal proceeding or for obtaining Registration abroad, \n NOTE- Upon any change of ownership of this Trade mark, or change in address, application should AT ONCE be made to the registrar to register the change";
    public static string GetPassage(int number, string type, string name, string address, string title)
    {
        return number switch
        {
            1 => $"Whereas a request for the grant of a {type} has been made by {name}, {address}",
            2 => $"For the sole use and advantage of an invention for {title}",
        };
    }
    
    public static string AssPassage2 = " with the following details";
}

public enum CldxCountry
{
    Afghanistan = 1,
    AlandIslands = 2,
    Albania = 3,
    Algeria = 4,
    AmericanSamoa = 5,
    Andorra = 6,
    Angola = 7,
    Anguilla = 8,
    Antarctica = 9,
    AntiguaAndBarbuda = 10,
    Argentina = 11,
    Armenia = 12,
    Aruba = 13,
    Australia = 14,
    Austria = 15,
    Azerbaijan = 16,
    Bahamas = 17,
    Bahrain = 18,
    Bangladesh = 19,
    Barbados = 20,
    Belarus = 21,
    Belgium = 22,
    Belize = 23,
    Benin = 24,
    Bermuda = 25,
    Bhutan = 26,
    Bolivia = 27,
    BosniaAndHerzegovina = 28,
    Botswana = 29,
    BouvetIsland = 30,
    Brazil = 31,
    BritishIndianOceanTerritory = 32,
    BruneiDarussalam = 33,
    Bulgaria = 34,
    BurkinaFaso = 35,
    Burundi = 36,
    Cambodia = 37,
    Cameroon = 38,
    Canada = 39,
    CapeVerde = 40,
    CaymanIslands = 41,
    CentralAfricanRepublic = 42,
    Chad = 43,
    Chile = 44,
    China = 45,
    ChristmasIsland = 46,
    CocosIslands = 47,
    Colombia = 48,
    Comoros = 49,
    Congo = 50,
    CongoDemocraticRepublic = 51,
    CookIslands = 52,
    CostaRica = 53,
    CoteDIvoire = 54,
    Croatia = 55,
    Cuba = 56,
    Cyprus = 57,
    CzechRepublic = 58,
    Denmark = 59,
    Djibouti = 60,
    Dominica = 61,
    DominicanRepublic = 62,
    Ecuador = 63,
    Egypt = 64,
    ElSalvador = 65,
    EquatorialGuinea = 66,
    Eritrea = 67,
    Estonia = 68,
    Ethiopia = 69,
    FalklandIslands = 70,
    FaroeIslands = 71,
    Fiji = 72,
    Finland = 73,
    France = 74,
    FrenchGuiana = 75,
    FrenchPolynesia = 76,
    FrenchSouthernTerritories = 77,
    Gabon = 78,
    Gambia = 79,
    Georgia = 80,
    Germany = 81,
    Ghana = 82,
    Gibraltar = 83,
    Greece = 84,
    Greenland = 85,
    Grenada = 86,
    Guadeloupe = 87,
    Guam = 88,
    Guatemala = 89,
    Guernsey = 90,
    Guinea = 91,
    GuineaBissau = 92,
    Guyana = 93,
    Haiti = 94,
    HeardIslandAndMcdonaldIslands = 95,
    HolySeeVaticanCity = 96,
    Honduras = 97,
    HongKong = 98,
    Hungary = 99,
    Iceland = 100,
    India = 101,
    Indonesia = 102,
    Iran = 103,
    Iraq = 104,
    Ireland = 105,
    IsleOfMan = 106,
    Israel = 107,
    Italy = 108,
    Jamaica = 109,
    Japan = 110,
    Jersey = 111,
    Jordan = 112,
    Kazakhstan = 113,
    Kenya = 114,
    Kiribati = 115,
    NorthKorea = 116,
    SouthKorea = 117,
    Kuwait = 118,
    Kyrgyzstan = 119,
    Laos = 120,
    Latvia = 121,
    Lebanon = 122,
    Lesotho = 123,
    Liberia = 124,
    Libya = 125,
    Liechtenstein = 126,
    Lithuania = 127,
    Luxembourg = 128,
    Macao = 129,
    Macedonia = 130,
    Madagascar = 131,
    Malawi = 132,
    Malaysia = 133,
    Maldives = 134,
    Mali = 135,
    Malta = 136,
    MarshallIslands = 137,
    Martinique = 138,
    Mauritania = 139,
    Mauritius = 140,
    Mayotte = 141,
    Mexico = 142,
    Micronesia = 143,
    Moldova = 144,
    Monaco = 145,
    Mongolia = 146,
    Montserrat = 147,
    Morocco = 148,
    Mozambique = 149,
    Myanmar = 150,
    Namibia = 151,
    Nauru = 152,
    Nepal = 153,
    Netherlands = 154,
    NetherlandsAntilles = 155,
    NewCaledonia = 156,
    NewZealand = 157,
    Nicaragua = 158,
    Niger = 159,
    Nigeria = 160,
    Niue = 161,
    NorfolkIsland = 162,
    NorthernMarianaIslands = 163,
    Norway = 164,
    Oman = 165,
    Pakistan = 166,
    Palau = 167,
    Palestine = 168,
    Panama = 169,
    PapuaNewGuinea = 170,
    Paraguay = 171,
    Peru = 172,
    Philippines = 173,
    Pitcairn = 174,
    Poland = 175,
    Portugal = 176,
    PuertoRico = 177,
    Qatar = 178,
    Reunion = 179,
    Romania = 180,
    Russia = 181,
    Rwanda = 182,
    SaintHelena = 183,
    SaintKittsAndNevis = 184,
    SaintLucia = 185,
    SaintPierreAndMiquelon = 186,
    SaintVincentAndTheGrenadines = 187,
    Samoa = 188,
    SanMarino = 189,
    SaoTomeAndPrincipe = 190,
    SaudiArabia = 191,
    Senegal = 192,
    SerbiaAndMontenegro = 193,
    Seychelles = 194,
    SierraLeone = 195,
    Singapore = 196,
    Slovakia = 197,
    Slovenia = 198,
    SolomonIslands = 199,
    Somalia = 200,
    SouthAfrica = 201,
    SouthGeorgiaAndSandwichIslands = 202,
    Spain = 203,
    SriLanka = 204,
    Sudan = 205,
    Suriname = 206,
    SvalbardAndJanMayen = 207,
    Swaziland = 208,
    Sweden = 209,
    Switzerland = 210,
    Syria = 211,
    Taiwan = 212,
    Tajikistan = 213,
    Tanzania = 214,
    Thailand = 215,
    TimorLeste = 216,
    Togo = 217,
    Tokelau = 218,
    Tonga = 219,
    TrinidadAndTobago = 220,
    Tunisia = 221,
    Turkey = 222,
    Turkmenistan = 223,
    TurksAndCaicosIslands = 224,
    Tuvalu = 225,
    Uganda = 226,
    Ukraine = 227,
    UnitedArabEmirates = 228,
    UnitedKingdom = 229,
    UnitedStates = 230,
    UnitedStatesMinorOutlyingIslands = 231,
    Uruguay = 232,
    Uzbekistan = 233,
    Vanuatu = 234,
    Venezuela = 235,
    Vietnam = 236,
    VirginIslandsBritish = 237,
    VirginIslandsUS = 238,
    WallisAndFutuna = 239,
    WesternSahara = 240,
    Yemen = 241,
    Zambia = 242,
    Zimbabwe = 243,
    NotSpecified = 244,
    Curacao = 245,
    BritishVirginIslands = 246,
    EurasianEAPO = 247,
    EuropeanCommunityEM = 248,
    EuropeanEP = 249,
    EuropeanCommunityEU = 250,
    WestIndies = 251,
    KingdomOfSaudiArabia = 252,
    Serbia = 254,
    RepublicOfChina = 255
}
